# Generated by Django 5.1 on 2024-10-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_useraccount_image_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='current_location',
            field=models.CharField(blank=True, choices=[('Uttara', 'UTTARA'), ('Mirpur', 'MIRPUR'), ('Dhanmondi', 'DHANMONDI')], max_length=20),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.URLField(blank=True, default='https://img.freepik.com/premium-photo/poster-anime-character-with-fiery-background_943629-32000.jpg', null=True),
        ),
    ]
