# Generated by Django 5.1 on 2024-10-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_useraccount_current_location_alter_useraccount_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='current_location',
            field=models.CharField(blank=True, choices=[('Uttara', 'UTTARA'), ('Mirpur', 'MIRPUR'), ('Dhanmondi', 'DHANMONDI')], default='UTTARA', max_length=20),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.URLField(blank=True, default='https://img.freepik.com/free-photo/androgynous-avatar-non-binary-queer-person_23-2151100183.jpg', null=True),
        ),
    ]
