# Generated by Django 5.1 on 2024-10-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_useraccount_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.URLField(blank=True, default='https://img.freepik.com/free-photo/anime-style-character-space_23-2151134190.jpg', null=True),
        ),
    ]
