# Generated by Django 5.1 on 2024-10-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='location',
            field=models.CharField(blank=True, choices=[('Uttara', 'UTTARA'), ('Mirpur', 'MIRPUR'), ('Dhanmondi', 'DHANMONDI')], max_length=20),
        ),
    ]
